[project]
name = "project"
version = "0.1.0"
requires-python = ">=3.12.0"
dependencies = [
  "gym>=0.26.2",
  "matplotlib>=3.10.3",
  "numpy>=2.3.1",
  "pygame>=2.6.1",
  "seaborn>=0.13.2",
]

[[tool.uv.index]]
name = "pytorch-cu126"
url = "https://download.pytorch.org/whl/cu126"
explicit = true
